# Generated by Django 5.1.3 on 2024-12-18 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_remove_investmentplan_monthly_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='last_earning_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
