# Generated by Django 5.1.3 on 2024-12-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_userreferral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferral',
            name='referral_code',
            field=models.CharField(default='A7A6C89F1F71', max_length=12, unique=True),
        ),
    ]
